name: Run content tests on PR

on:
  pull_request:
    types:
      - opened
      - edited

  push:
    branches: [ develop, main, stage ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - uses: actions/checkout@v2
    - name: Test content
      run: |
        bash .github/workflows/testContent.sh
